<?php 
$jugadores = [
    "Amador" => ["País" => "España", "Dorsal" => 13, "Nacimiento" => "1/12/1976", "Posición" => "Delantero", "Goles" => mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Arturo" => ["País" => "Chile", "Dorsal" => 8, "Nacimiento" => "22/5/1987", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Cristiano" => ["País" => "Portugal", "Dorsal" => 7, "Nacimiento" => "5/2/1985", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Haaland" => ["País" => "Noruega", "Dorsal" => 9, "Nacimiento" => "21/7/2000", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Jordi" => ["País" => "España", "Dorsal" => 11, "Nacimiento" => "11/9/1994", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Mbappe" => ["País" => "Francia", "Dorsal" => 12, "Nacimiento" => "20/12/1998", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Messi" => ["País" => "Argentina", "Dorsal" => 10, "Nacimiento" => "24/6/1987", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Morata" => ["País" => "España", "Dorsal" => 14, "Nacimiento" => "23/10/1992", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Nines" => ["País" => "España", "Dorsal" => 1, "Nacimiento" => "8/4/1971", "Posición" => "Portero", "Goles atajados" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Puyol" => ["País" => "España", "Dorsal" => 16, "Nacimiento" => "13/4/1978", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Ronaldinho" => ["País" => "Brasil", "Dorsal" => 18, "Nacimiento" => "21/3/1980", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Ronaldo" => ["País" => "Brasil", "Dorsal" => 17, "Nacimiento" => "18/9/1976", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Samu" => ["País" => "Camerún", "Dorsal" => 19, "Nacimiento" => "10/3/1981", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Sturridge" => ["País" => "REino Unido", "Dorsal" => 20, "Nacimiento" => "1/9/1989", "Posición" => "Defensa", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Vinicius" => ["País" => "Brasil", "Dorsal" => 15, "Nacimiento" => "12/7/2000", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Zlatan" => ["País" => "Suecia", "Dorsal" => 6, "Nacimiento" => "3/10/1981", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Iniesta" => ["País" => "España", "Dorsal" => 5, "Nacimiento" => "11/5/1984", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Benzema" => ["País" => "Francia", "Dorsal" => 4, "Nacimiento" => "19/12/1987", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Lewandowski" => ["Polonia" => "España", "Dorsal" => 3, "Nacimiento" => "21/8/1988", "Posición" => "Delantero", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
    "Joaquin" => ["País" => "España", "Dorsal" => 2, "Nacimiento" => "21/7/1981", "Posición" => "Centrocampista", "Goles" =>  mt_rand(0, 16), "Partidos jugados" => mt_rand(0, 7)],
];